- platform: template
  sensors:
    hue_eldhus_battery:
      friendly_name: Eldhús Hue hreyfiskynjari
      unit_of_measurement: "%"
      value_template: "{{state_attr('binary_sensor.eldhus_motion_sensor', 'battery')}}"
    hue_bilskur_battery:
      friendly_name: Bílskúr Hue hreyfiskynjari
      unit_of_measurement: "%"
      value_template: "{{state_attr('binary_sensor.bilskur_motion_sensor', 'battery')}}"
    hue_klosett_nidri_battery:
      friendly_name: Klósett niðri Hue hreyfiskynjari
      unit_of_measurement: "%"
      value_template: "{{state_attr('binary_sensor.klosett_nidri_motion_sensor', 'battery')}}"
    hue_klosett_uppi_battery:
      friendly_name: Klósett uppi Hue hreyfiskynjari
      unit_of_measurement: "%"
      value_template: "{{state_attr('binary_sensor.klosett_uppi_motion_sensor', 'battery')}}"
    eldhus_vaskur_l_color:
      value_template: >-
        {% if is_state('light.eldhus_vaskur_l', 'off') %}
          0
        {% else %}
          {% if state_attr('light.eldhus_vaskur_l','color_temp')%}
            60
          {% else %}
            {% set x = state_attr('light.eldhus_vaskur_l', 'hs_color') | regex_replace(find=',.*', replace='', ignorecase=false) | replace('(', '') | float %}
            {{ x }}
          {% endif %}
        {% endif %}
    eldhus_vaskur_m_color:
      value_template: >-
        {% if is_state('light.eldhus_vaskur_m', 'off') %}
          0
        {% else %}
          {% if state_attr('light.eldhus_vaskur_m','color_temp')%}
            60
          {% else %}
            {% set x = state_attr('light.eldhus_vaskur_m', 'hs_color') | regex_replace(find=',.*', replace='', ignorecase=false) | replace('(', '') | float %}
            {{ x }}
          {% endif %}
        {% endif %}
    eldhus_vaskur_r_color:
      value_template: >-
        {% if is_state('light.eldhus_vaskur_r', 'off') %}
          0
        {% else %}
          {% if state_attr('light.eldhus_vaskur_r','color_temp')%}
            60
          {% else %}
            {% set x = state_attr('light.eldhus_vaskur_r', 'hs_color') | regex_replace(find=',.*', replace='', ignorecase=false) | replace('(', '') | float %}
            {{ x }}
          {% endif %}
        {% endif %}
    forstofa_color:
      value_template: >-
        {% if is_state('light.forstofa', 'off') %}
          0
        {% else %}
          {% if state_attr('light.forstofa','color_temp')%}
            60
          {% else %}
            {% set x = state_attr('light.forstofa', 'hs_color') | regex_replace(find=',.*', replace='', ignorecase=false) | replace('(', '') | float %}
            {{ x }}
          {% endif %}
        {% endif %}
    saevar_color:
      value_template: >-
        {% if is_state('light.saevar', 'off') %}
          0
        {% else %}
          {% if state_attr('light.saevar','color_temp')%}
            60
          {% else %}
            {% set x = state_attr('light.saevar', 'hs_color') | regex_replace(find=',.*', replace='', ignorecase=false) | replace('(', '') | float %}
            {{ x }}
          {% endif %}
        {% endif %}
    saevar_lampi_color:
      value_template: >-
        {% if is_state('light.saevar_lampi', 'off') %}
          0
        {% else %}
          {% if state_attr('light.saevar_lampi','color_temp')%}
            60
          {% else %}
            {% set x = state_attr('light.saevar_lampi', 'hs_color') | regex_replace(find=',.*', replace='', ignorecase=false) | replace('(', '') | float %}
            {{ x }}
          {% endif %}
        {% endif %}
    kolbrun_color:
      value_template: >-
        {% if is_state('light.kolbrun', 'off') %}
          0
        {% else %}
          {% if state_attr('light.kolbrun','color_temp')%}
            60
          {% else %}
            {% set x = state_attr('light.kolbrun', 'hs_color') | regex_replace(find=',.*', replace='', ignorecase=false) | replace('(', '') | float %}
            {{ x }}
          {% endif %}
        {% endif %}
    dagmar_color:
      value_template: >-
        {% if is_state('light.dagmar', 'off') %}
          0
        {% else %}
          {% if state_attr('light.dagmar','color_temp')%}
            60
          {% else %}
            {% set x = state_attr('light.dagmar', 'hs_color') | regex_replace(find=',.*', replace='', ignorecase=false) | replace('(', '') | float %}
            {{ x }}
          {% endif %}
        {% endif %}
    stofulampi_color:
      value_template: >-
        {% if is_state('light.stofulampi', 'off') %}
          0
        {% else %}
          {% if state_attr('light.stofulampi','color_temp')%}
            60
          {% else %}
            {% set x = state_attr('light.stofulampi', 'hs_color') | regex_replace(find=',.*', replace='', ignorecase=false) | replace('(', '') | float %}
            {{ x }}
          {% endif %}
        {% endif %}
    utiljos_color:
      value_template: >-
        {% if is_state('light.utiljos', 'off') %}
          0
        {% else %}
          {% if state_attr('light.utiljos','color_temp')%}
            60
          {% else %}
            {% set x = state_attr('light.utiljos', 'hs_color') | regex_replace(find=',.*', replace='', ignorecase=false) | replace('(', '') | float %}
            {{ x }}
          {% endif %}
        {% endif %}
    forstofa_test_color:
      value_template: >-
        {% if is_state('light.forstofa', 'off') %}
          0
        {% else %}
          {% if state_attr('light.forstofa','color_temp')%}
            60
          {% else %}
            {% set x = state_attr('light.forstofa', 'hs_color') | regex_replace(find=',.*', replace='', ignorecase=false) | replace('(', '') | float %}
            {{ x }}
          {% endif %}
        {% endif %}